version: '2.4'
services:
  home_codes:
    container_name: home_codes
    build: .
    volumes: 
      - type: bind 
        source: ./config.json
        target: /config.json

    ports:
      - "1987:8080"